## 05 ``numpy.array`` 基本操作

In [7]:
import numpy as np
np.random.seed(0)

x = np.arange(10)

In [4]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

reshape 可以把一维 变成 二维

In [9]:
X = np.arange(15).reshape((3, 5))  

In [6]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### ``numpy.array`` 的基本属性

#### ``ndim`` 表示维数

In [18]:
x.ndim

1

In [19]:
X.ndim

2

#### ``shape`` 表示size  (10,)表示一维数组

In [20]:
x.shape

(10,)

In [21]:
X.shape

(3, 5)

#### ``size`` 元素个数

In [22]:
x.size

10

In [23]:
X.size

15

### ``numpy.array`` 的数据访问

In [24]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
x[0]

0

In [14]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
X[0][0] # 不建议！

0

In [27]:
X[0, 0]

0

In [29]:
X[(0, -1)] #可以把()省略掉 访问

4

In [30]:
X[0, -1]

4

In [18]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
x[0:5] #切片 [start,end)

array([0, 1, 2, 3, 4])

In [33]:
x[:5] #从头

array([0, 1, 2, 3, 4])

In [34]:
x[5:] #到尾

array([5, 6, 7, 8, 9])

In [22]:
x[4:7]

array([4, 5, 6])

In [35]:
x[::2] #从头到尾 步长为2

array([0, 2, 4, 6, 8])

In [36]:
x[1::2]

array([1, 3, 5, 7, 9])

In [37]:
x[::-1] # 倒着输出

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [26]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [42]:
X[:2, :3] #前两行，前三列  ！！！！ 取元素 用这个

array([[0, 1, 2],
       [5, 6, 7]])

In [43]:
X[:2] #前两行

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
X[:2][:3] # 本意是取前3个元素，但是这个数组只有2个元素   结果不一样，在numpy中使用","做多维索引

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
X[:2][:1]

array([[0, 1, 2, 3, 4]])

In [45]:
X[:2, ::2] # 前两行 所有间隔为2的元素

array([[0, 2, 4],
       [5, 7, 9]])

In [46]:
X[::-1, ::-1] # 行列都倒着  矩阵反转

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [47]:
X[0]   #取出第一行

array([0, 1, 2, 3, 4])

In [48]:
X[0, :] #取出第一行  (行取0，列从头到尾)

array([0, 1, 2, 3, 4])

In [49]:
X[0, :].ndim

1

In [50]:
X[:, 0] # 取出第一列 （行头到尾，列取0）

array([ 0,  5, 10])

### Subarray of ``numpy.array``

In [51]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

改变子矩阵，原矩阵变化

In [52]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

#### python中的切片是新的矩阵，原矩阵不会改变
#### numpy.array 中的子矩阵值变化时，原矩阵也会发生变化 （引用）

In [54]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [55]:
X[0, 0] = 0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [37]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

和原矩阵脱离关系 copy

In [56]:
subX = X[:2, :3].copy()

In [57]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [58]:
X #原矩阵不发生变化

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Reshape （不改变原矩阵）

In [59]:
x.shape

(10,)

In [60]:
x.ndim

1

In [43]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
A = x.reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
B = x.reshape(1, 10) #二维
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [62]:
B.ndim

2

In [63]:
B.shape

(1, 10)

In [50]:
x.reshape(-1, 10) #指定列数为10   行数不指定 （自动算）

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [51]:
x.reshape(10, -1) #指定行数为10   列数不指定（自动算）

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [52]:
x.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [53]:
x.reshape(3, -1)

ValueError: cannot reshape array of size 10 into shape (3,newaxis)