## 04 创建 ``numpy.array``

In [5]:
import numpy as np

### ``numpy.array``

传入list

In [2]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 其他创建 ``numpy.array`` 的方法

#### ``zeros`` （shape=数据，dtype=类型）默认浮点型 

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros(10, dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

 元组（行,列） 三行五列

In [20]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.zeros(shape=(3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

#### ones  填充1  默认浮点型 

In [23]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### full 的 fill_value默认不是浮点型

In [32]:
np.full((3, 5), 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

当显式的给属性赋值时，参数的顺序可以发生变化

In [33]:
np.full(fill_value=666.0, shape=(3, 5))

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

只有一个参数时，不写参数名是可以的，但是有多个参数会引起歧义，最好写上

In [6]:
np.full(fill_value=12, shape=10)

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

#### arange

#### Python中  range(start,end,step)  [start,end) 前闭后开

In [7]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [12]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

python range 的步长step不能是浮点数 

In [11]:
[i for i in range(0, 1, 0.2)]  

TypeError: 'float' object cannot be interpreted as an integer

np 可以把步长传入浮点数

In [12]:
np.arange(0, 1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [13]:
[i for i in range(0, 10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

只有一个参数，省略了起始点 默认为0

In [17]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### linspace(start,end,点的数目) 生成等差数列 [start,end]  包括end点

In [22]:
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [23]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [24]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### random

##### randint（start,end,size）生成整数  size=向量(数组)【start,end） 前闭后开

In [48]:
np.random.randint(0, 10)    # [0, 10)之间的随机数

4

In [49]:
np.random.randint(0, 10, 3)

array([4, 0, 0])

In [50]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
np.random.randint(0, 10, size=10)

array([4, 0, 4, 5, 7, 1, 0, 0, 6, 6])

In [52]:
np.random.randint(0, 10, size=(3,5))

array([[0, 3, 2, 9, 2],
       [6, 0, 6, 0, 9],
       [3, 6, 9, 3, 2]])

(end,size) start可以省略 --> 0 

In [44]:
np.random.randint(10, size=(3,5))

array([[1, 9, 0, 0, 5],
       [3, 8, 8, 2, 0],
       [6, 1, 6, 3, 1]])

随机数-->伪随机数-->通过随机种子生成-->种子一样，生成的随机数就是一样的

##### seed

In [45]:
np.random.seed(666)

In [46]:
np.random.randint(0, 10, size=(3, 5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

In [47]:
np.random.seed(666)
np.random.randint(0, 10, size=(3,5))

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

##### random(size) [0,1)  默认生成浮点数

In [55]:
np.random.random()

0.570436726659945

In [56]:
np.random.random((4))

array([0.57773404, 0.89274848, 0.12138544, 0.66083873])

In [57]:
np.random.random((3,5))

array([[0.16459271, 0.09435837, 0.5876144 , 0.86014445, 0.82936987],
       [0.65091808, 0.51832728, 0.00355049, 0.80309176, 0.35932938],
       [0.42014544, 0.2026436 , 0.63279787, 0.18935861, 0.1308497 ]])

##### normal(Ex,Dx,size) 符合正态分布的随机数 size=值 /元组

In [63]:
np.random.normal() #正态分布均值为0 方差为1的随机数

0.05738819741420407

In [64]:
np.random.normal(10, 100)

-146.00397611081334

In [71]:
np.random.normal(0, 1, (3, 5))

array([[-0.16835626, -0.76976762, -0.88850405,  0.31013719, -0.36922427],
       [-0.19689097, -0.20295687, -0.19861894,  1.50831817, -0.82574477],
       [-0.31945149, -0.03616602, -0.29822527,  0.0074711 ,  2.98832221]])

`np.random.<TAB>` 查看random中的更多方法/模块

In [70]:
np.random?

In [68]:
np.random.normal?

In [69]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the ``normal`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution