## 08 ``Numpy`` 中的聚合操作

### sum

In [1]:
import numpy as np

L = np.random.random(100)
sum(L) #python 自带的  效率低

51.43225242290165

In [2]:
np.sum(L)

51.43225242290166

In [7]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

73.7 ms ± 619 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
905 µs ± 49.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### min, max np和big都可以调用

In [8]:
np.min(big_array)

1.9131559977347834e-06

In [9]:
np.max(big_array)

0.9999995112755222

In [10]:
big_array.min()

1.9131559977347834e-06

In [11]:
big_array.max()

0.9999995112755222

In [12]:
big_array.sum()

500002.5709042231

### 多维度聚合

In [13]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
np.sum(X)

120

In [17]:
np.sum(X, axis=0) # 沿着行维度（压缩到行），把列加起来

array([24, 28, 32, 36])

In [18]:
np.sum(X, axis=1) # 沿着列维度（压缩到列），把行加起来

array([ 6, 22, 38, 54])

注意：axis描述的是将要被压缩的维度。

### 其他聚合操作

In [20]:
np.prod(X) #返回所有元素的乘积

0

In [21]:
np.prod(X + 1) # prod支持大数运算 

2004189184

In [22]:
np.mean(X) #求 平均值

7.5

In [23]:
np.median(X) #求 中位数

7.5

In [24]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [25]:
np.median(v)

2.0

q=50 ,与median 是一个值

In [34]:
np.percentile(big_array, q=50) #统计学中 百分位  ，q : 50%元素<0.5003

0.5003658997114797

In [35]:
np.median(big_array) # q=50 ,,,,但是percentile 可以求任意百分位的值

0.5003658997114797

q=100 ,与max 是一个值

In [36]:
np.percentile(big_array, q=100) 

0.9999995112755222

In [37]:
np.max(big_array)

0.9999995112755222

q=0 ,与min 是一个值

In [39]:
for percent in [0, 25, 50, 75, 100]: #常用5个值
    print(np.percentile(big_array, q=percent))

1.9131559977347834e-06
0.2500159936994241
0.5003658997114797
0.7501196307992014
0.9999995112755222


In [40]:
np.var(big_array) #求方差

0.08333756446269047

In [41]:
np.std(big_array) #求标准差

0.2886824630328113

In [42]:
x = np.random.normal(0, 1, size=1000000) # 正态分布

In [43]:
np.mean(x) 

-0.0004134439641764659

In [44]:
np.std(x)

0.9991434727920222