## 06 ``numpy.array`` 合并和分割

In [1]:
import numpy as np

### ``numpy.array`` 的合并

In [2]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [3]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [4]:
z = np.array([666, 666, 666])
# 合并三个数组
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [5]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
np.concatenate([A, A]) # 默认 axis=0，轴为行  沿着竖直方向拼接 行增加，列不变

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

轴为哪个，哪个方向增加

In [6]:
np.concatenate([A, A], axis=1) # axis=1，轴为列 沿着水平的方向拼接 行不变，列增加

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

`concatenate` 只能处理维数相同的矩阵  传入[]

In [7]:
np.concatenate([A, z]) #concatenate 只能处理维数相同的矩阵

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
# 升维数 [[666 666 666]]

In [8]:
np.concatenate([A, z.reshape(1, -1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

`vstack` 维数不同也可以，垂直 叠加 传入[]

In [9]:
np.vstack([A,z])  # z一维的竖直叠加

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [10]:
B = np.full((2,2), 100)
print(B)         # B二维的水平叠加 

[[100 100]
 [100 100]]


`hstack` 维数不同也可以，水平 叠加 传入[]

In [11]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [12]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
z

array([666, 666, 666])

In [14]:
np.hstack([A, z]) #数据要合法，，行数不一致，无法水平合并

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

### ``numpy.array`` 的分割

In [15]:
x = np.arange(10)
x    

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`split`(x, [start,end])切割为三段数据 中间的数据 [start,end) 前闭后开

In [16]:
x1, x2, x3 = np.split(x, [3, 7])

In [17]:
x1

array([0, 1, 2])

In [18]:
x2

array([3, 4, 5, 6])

In [19]:
x3

array([7, 8, 9])

`split`(x, [mid]) 切割为两段数据 mid在第二段数据包含

In [20]:
x1, x2 = np.split(x, [5])

In [21]:
x1

array([0, 1, 2, 3, 4])

In [22]:
x2

array([5, 6, 7, 8, 9])

In [23]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

`split` 对于二维数据的参数变化： 默认axis=0分割行，axis=1分割列

In [24]:
A1, A2 = np.split(A, [2])

In [25]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [26]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
A1, A2 = np.split(A, [2], axis=1)

In [28]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [29]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

`vsplit`()垂直分割 

In [30]:
upper, lower = np.vsplit(A, [2])

In [31]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [32]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

`hsplit`()水平分割

In [33]:
left, right = np.hsplit(A, [2])

In [34]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [35]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [36]:
data = np.arange(16).reshape((4, 4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

##### np.hsplit(data, [-1])

In [41]:
X, y = np.hsplit(data, [-1])#-1 在后面的矩阵，这样就把数据格式分好了

In [42]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [43]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

##### y[:, 0] ->向量(一维)

In [47]:
y[:, 0] #所有行，第0列  逆置

array([ 3,  7, 11, 15])