## 10 ``Numpy`` 中的比较和Fancy Indexing

### Fancy Indexing

In [1]:
import numpy as np

x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [2]:
x[3]

3

In [3]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [4]:
x[3:9:2] # 第三个参数 是 步长

array([3, 5, 7])

In [5]:
[x[3], x[5], x[8]] # 非等步长

[3, 5, 8]

In [6]:
ind = [3, 5, 7] #只要把索引放进去，就可以得到索引对应值的向量  此例子索引与值恰好一样
x[ind]

array([3, 5, 7])

In [7]:
ind = np.array([[0, 2], [1, 3]]) #把索引二维格式放进去，得到二维矩阵
x[ind]

array([[0, 2],
       [1, 3]])

#### Fancy Indexing 应用在二维数组

In [8]:
X = x.reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
X[row, col]

array([ 1,  6, 11])

In [10]:
X[0, col] # 行：0

array([1, 2, 3])

In [11]:
X[:2, col] # 前两行

array([[1, 2, 3],
       [5, 6, 7]])

In [12]:
col = [True, False, True, True]

In [13]:
X[1, col]

array([4, 6, 7])

### ``numpy.array`` 的比较  布尔值

In [14]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
x < 3 

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [16]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [17]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [18]:
x >= 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [19]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [20]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [21]:
2 * x == 24 - 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [22]:
X < 6  # 二维比较

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

### 使用 ``numpy.array`` 的比较结果 

In [23]:
np.count_nonzero( x <= 3) # 数出来 传入的数组有多少非零元素

4

In [24]:
np.sum(x <= 3)  # 加起来

4

In [25]:
np.sum(X % 2 == 0, axis=0) # 沿着x方向，偶数， 列 数目加起来

array([4, 0, 4, 0])

In [26]:
np.sum(X % 2 == 0, axis=1) # 沿着y方向，偶数， 行 数目加起来

array([2, 2, 2, 2])

In [27]:
np.any(x == 0) # 是否有为0的元素

True

In [28]:
np.any(x < 0)  # 是否有 < 0的元素

False

In [29]:
np.all(x > 0)  # 是否所有元素大于0

False

In [30]:
np.all(x >= 0)

True

In [31]:
np.all(X > 0, axis=1)

array([False,  True,  True,  True])

In [32]:
np.sum((x > 3) & (x < 10)) # & 位运算 把每一个元素一一对应运算，左右都是数组-->得到也是数组

6

In [33]:
np.sum((x > 3) && (x < 10)) # &&条件运算符，连接两个布尔值-->得到也是布尔值

SyntaxError: invalid syntax (<ipython-input-33-1358aa8e7f43>, line 1)

In [34]:
np.sum((x % 2 == 0) | (x > 10)) # 或运算

11

In [35]:
np.sum(~(x == 0)) # 非运算

15

### 比较结果和Fancy Indexing

In [36]:
x < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [37]:
x[x < 5] # 下标->值

array([0, 1, 2, 3, 4])

In [40]:
x % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False])

In [44]:
x[x % 2 == 0] # 下标->值偶数值

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [45]:
X[:,3] #在最后一列 二维 特征值被3整除

array([ 3,  7, 11, 15])

In [46]:
X[:,3] % 3 == 0

array([ True, False, False,  True])

In [47]:
X[X[:,3] % 3 == 0, :] 

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])