## 09 ``Numpy`` 中arg运算

In [1]:
import numpy as np

In [2]:
x = np.random.normal(0, 1, 1000000)

### 索引

In [3]:
np.argmin(x) #找到最小值的索引

617038

In [9]:
x[617038]

-5.277820073031027

In [10]:
np.min(x)

-5.277820073031027

In [11]:
np.argmax(x) #找到最大值的索引

784049

In [13]:
x[784049] 

4.928339081694574

In [14]:
np.max(x)

4.928339081694574

### 排序和使用索引

In [15]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [16]:
np.random.shuffle(x)
x

array([ 5, 11,  9, 13,  0, 14, 10,  2, 12,  7, 15,  3,  8,  6,  1,  4])

In [19]:
np.sort(x) # 不改变原数组

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [20]:
x

array([ 5, 11,  9, 13,  0, 14, 10,  2, 12,  7, 15,  3,  8,  6,  1,  4])

In [21]:
x.sort() # 改变原数组 直接对 数组 操作

In [22]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [23]:
X = np.random.randint(10, size=(4,4))
X

array([[6, 0, 4, 2],
       [8, 4, 0, 6],
       [5, 7, 0, 4],
       [9, 8, 2, 5]])

In [32]:
np.sort(X, axis=1) # 沿着纵轴方向 压缩 y 轴，行排序  ！！！ 默认值 axis = 1

array([[0, 2, 4, 6],
       [0, 4, 6, 8],
       [0, 4, 5, 7],
       [2, 5, 8, 9]])

In [33]:
np.sort(X, axis=0) # 沿着横轴方向 压缩 x 轴，列排序

array([[5, 0, 0, 2],
       [6, 4, 0, 4],
       [8, 7, 2, 5],
       [9, 8, 4, 6]])

#### 使用索引

In [34]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [35]:
np.random.shuffle(x)

In [36]:
x

array([15,  6,  1,  5, 10,  8, 13,  9,  0, 14, 11, 12,  7,  4,  3,  2])

In [38]:
np.argsort(x) # 索引的值 是排序的

array([ 8,  2, 15, 14, 13,  3,  1, 12,  5,  7,  4, 10, 11,  6,  9,  0],
      dtype=int64)

In [41]:
np.partition(x, 3)  #类似快排的 支点，用支点的数值大小进行二分
# 3前面的数字比3都要小，后面的数字比3都要大

array([ 2,  0,  1,  3,  5,  8,  4,  6,  7,  9, 11, 12, 14, 13, 10, 15])

In [43]:
np.argpartition(x, 3) # 比3（索引为 14）小的索引 大的索引

array([15,  8,  2, 14,  3,  5, 13,  1, 12,  7, 10, 11,  9,  6,  4,  0],
      dtype=int64)

In [49]:
X

array([[6, 0, 4, 2],
       [8, 4, 0, 6],
       [5, 7, 0, 4],
       [9, 8, 2, 5]])

In [51]:
np.argsort(X, axis=1) # 行排序 里面都是索引

array([[1, 3, 2, 0],
       [2, 1, 3, 0],
       [2, 3, 0, 1],
       [2, 3, 1, 0]], dtype=int64)

In [52]:
np.argpartition(X, 2, axis=1) # 列排序 里面都是索引

array([[1, 3, 2, 0],
       [2, 1, 3, 0],
       [2, 3, 0, 1],
       [2, 3, 1, 0]], dtype=int64)