## 03 ``numpy.array`` 基础

In [2]:
import numpy

In [3]:
numpy.__version__

'1.20.1'

In [4]:
import numpy as np

In [5]:
np.__version__

'1.20.1'

### Python List的特点

In [6]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
L[5]

5

In [8]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [10]:
L[5] = "Machine Learning" #类型可以不同
L

[0, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

Python的List不要求存储同样的类型，带来效率问题。 array的类型必须一致

In [13]:
import array
arr = array.array('i',[i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr[5]

5

In [15]:
arr[5] = 100
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [16]:
arr[5] = "Machine Learning"

TypeError: an integer is required (got type str)

In [17]:
arr[5] = 5.0

TypeError: integer argument expected, got float

``array``缺点：没有将数据当做向量或者矩阵，不支持基本运算。
只是将存储在其中的数据当作一个（二维）数组来看，但是无论基于数组还是二维数组，它没有将这些数据看作向量或者矩阵，相应的也没有为这些数据配备和向量相关或者矩阵相关的运算，使得机器学习中使用array也不方便。

### ``numpy.array``

可以传list

In [19]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [21]:
nparr[5] = "Machine Learning"

ValueError: invalid literal for int() with base 10: 'Machine Learning'

 查看 ``nparr`` 类型 ：  dtype 方法

In [24]:
nparr.dtype 

dtype('int32')

In [26]:
nparr[5] = 5.0
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
nparr.dtype

dtype('int32')

``nparr`` 只接受整型 小数->隐式的类型转换

In [30]:
nparr[5] = 3.14
nparr

array([0, 1, 2, 3, 4, 3, 6, 7, 8, 9])

In [31]:
nparr2 = np.array([1, 2, 3.0])
nparr2.dtype

dtype('float64')

``nparr`` 在创建的时候指定类型