## 02 scikit-learn 中的 kNN 

In [13]:
import numpy as np
import matplotlib.pyplot as plt

In [14]:
raw_data_X = [[3.393533211, 2.331273381],
              [3.110073483, 1.781539638],
              [1.343808831, 3.368360954],
              [3.582294042, 4.679179110],
              [2.280362439, 2.866990263],
              [7.423436942, 4.696522875],
              [5.745051997, 3.533989803],
              [9.172168622, 2.511101045],
              [7.792783481, 3.424088941],
              [7.939820817, 0.791637231]
             ]
raw_data_y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]

X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)

x = np.array([8.093607318, 3.365731514])

In [39]:
%run kNN_function/kNN.py  # 加载函数

In [40]:
predict_y = kNN_classify(6, X_train, y_train, x)

In [41]:
predict_y

1

### 使用scikit-learn中的kNN

都是以面向对象的形式封装的，先要实例化

In [18]:
from sklearn.neighbors import KNeighborsClassifier

In [19]:
kNN_classifier = KNeighborsClassifier(n_neighbors=6) #构造函数  n_neighbors是固定的

机器学习算法要先拟合fit

In [20]:
kNN_classifier.fit(X_train, y_train) # fit ：拟合

KNeighborsClassifier(n_neighbors=6)

不管数据量多少，整理成矩阵形式

In [42]:
kNN_classifier.predict(x)

ValueError: Expected 2D array, got 1D array instead:
array=[8.09360732 3.36573151].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [26]:
X_predict = x.reshape(1, -1) # 必须是矩阵  一个数据，第一个维度为1.第二个维度任意

In [27]:
X_predict

array([[8.09360732, 3.36573151]])

In [28]:
kNN_classifier.predict(X_predict)

array([1])

In [29]:
y_predict = kNN_classifier.predict(X_predict)

In [30]:
y_predict[0]

1

### 重新整理我们的kNN的代码

代码参见 [这里](kNN/KNN.py)

In [44]:
%run kNN/kNN.py

In [45]:
knn_clf = KNNClassifier(3)

In [46]:
knn_clf.fit(X_train, y_train)

KNN(k=3)

In [47]:
y_predict = knn_clf.predict(X_predict)

In [48]:
y_predict

array([1])

In [49]:
y_predict[0]

1